type AboutProps = {
  isOpen: boolean;
  onClose: () => void;
};

function About({ isOpen, onClose }: AboutProps) {
  if (isOpen === false) {
    return null;
  }
  return (
    <div className="fixed inset-0 flex items-center justify-center z-40 px-6">
      <div className="glassy border border-white rounded-2xl p-8 max-w-2xl w-full z-50">
        <h2 className="text-3xl text-center mb-6 text-white under">About LeetMonkey</h2>
        <div className="rounded-full h-50 w-50 mx-auto">
          <img
            src="brandon-avatar-2.png"
            className="rounded-full h-50 w-50 object-cover"
            alt="Brandon Avatar"
          ></img>
        </div>
        <blockquote className="text-white leading-7 border-l-2 pl-8 my-8 py-6 border-amber-300 italic">
          Hi, I'm Brandon, and welcome to <strong>LeetMonkey</strong>! LeetMonkey is a daily practice
          platform designed to help you code faster and more efficiently. Each
          day, you're given one hand-picked challenge — and the full solution is
          provided. It's all about building speed, accuracy, and muscle memory
          through focused daily practice. This website was made using React and TailwindCSS.
          The solutions and explanations provided are a mix of my own insights as a developer 
          and answers generated by large language models (LLMs), all of which have been 
          reviewed and tested for accuracy. More features are on the way, and I'm
          excited to keep making LeetMonkey even better. LeetMonkey is inspired
          by LeetCode, NeetCode, and Leetle. Thanks for stopping by and being
          part of the journey! - <strong>BLT 🐒</strong>
        </blockquote>
        <p>
          Want to say hi?{" "}
          <a
            href="https://www.brandonleetran.com/drops"
            className="underline underline-offset-3 hover:text-white transition-all duration-200 cursor-pointer"
          >
            Leave me a note
          </a>
        </p>
        <p>
          Want to contribute?{" "}
          <a
            href="mailto:brandonleetran@icloud.com"
            className="underline underline-offset-3 hover:text-white transition-all duration-200 cursor-pointer"
          >
            Shoot me an email
          </a>
        </p>
        <p className="mb-10">
          Want to support LeetMonkey?{" "}
          <a
            href="https://buymeacoffee.com/brandonleetran"
            className="underline underline-offset-3 hover:text-white transition-all duration-200 cursor-pointer"
          >
            Buy me a coffee
          </a>
        </p>
        <small className="italic inline-block">
          Note: LeetMonkey is not affiliated with LeetCode.
        </small>
        <button
            className="absolute right-0 top-0 mt-5 mr-5 cursor-pointer"
            onClick={onClose}
            aria-label="Close modal"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              fill="currentColor"
              className="size-8 hover:text-white transition-all duration-200 cursor-pointer"
            >
              <path
                fillRule="evenodd"
                d="M12.97 3.97a.75.75 0 0 1 1.06 0l7.5 7.5a.75.75 0 0 1 0 1.06l-7.5 7.5a.75.75 0 1 1-1.06-1.06l6.22-6.22H3a.75.75 0 0 1 0-1.5h16.19l-6.22-6.22a.75.75 0 0 1 0-1.06Z"
                clipRule="evenodd"
              />
            </svg>
          </button>
      </div>
    </div>
  );
}

export default About;
